import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {runInNewContext} from 'node:vm';
import {erpTripFingerprint} from '../erp-first-trip.mjs';import {parseRequestTimelineTimestamp} from '../request-timeline.mjs';
const source=readFileSync(new URL('../server.mjs',import.meta.url),'utf8');const route=source.slice(source.indexOf("app.post('/api/requests/:reference/erp-first-trip'"),source.indexOf("app.patch('/api/requests/:reference/verify'"));
const row={ref:'R1',site:'Sasti',door:'D1',closedAt:'2026-10-01 09:00:00',status:'Closed',meterType:'HMR',closingMeterReading:'10',closingMeterReadings:{HMR:'10'}};
async function run({site='Sasti',state=row,status='ready',race=false}={}){let handler,reads=0,writes=[];const evidence={status,requestHash:erpTripFingerprint(state),sourceHash:'source',record:{source:'Equipment Log Book',documentNo:'E1'}};
 const context={Date,Intl,parseRequestTimelineTimestamp,erpTripFingerprint,app:{post(path,...handlers){handler=handlers.at(-1);}},requireSession(){},requirePermission:()=>()=>{},currentUserRecord:async()=>({site}),userSiteScope:u=>({sites:[u.site]}),reportScopeIncludesSite:(scope,s)=>scope.sites.includes(s),requestProjection:'*',isIdleVehicleRequest:r=>r.vehicleIdle===true,pool:{query:async()=>({rows:[structuredClone(state)]})},oracleFirstTripLog:async()=>{reads++;return evidence;},erpTripImage:async()=> 'data:image/png;base64,server',withRequestTimelineTransaction:async(req,ref,fn)=>fn({query:async(sql,args)=>{if(sql.startsWith('SELECT'))return {rows:[{...state,site:race?'Other':state.site}]};writes.push({sql,args});return {rows:[]};}}),maintenanceWriteFailure:(e,res)=>res.status(e.status||500).json({error:e.message})};
 runInNewContext(route,context);const res={statusCode:200,set(){},status(c){this.statusCode=c;return this;},json(body){this.body=body;return this;}};
 await handler({params:{reference:'R1'},session:{login:'mis'},body:{}},res,()=>{});return {res,reads,writes};}
test('ERP fetch enforces assigned site, closed/on-road status before reading Oracle',async()=>{for(const options of [{site:'Other'},{state:{...row,status:'In progress'}},{state:{...row,vehicleIdle:true}},{state:{...row,verifiedAt:'done'}}]){const result=await run(options);assert.ok(result.res.statusCode>=400);assert.equal(result.reads,0);assert.equal(result.writes.length,0);}});
test('pending ERP records cannot attach an image or verify a request',async()=>{const result=await run({status:'pending'});assert.equal(result.res.body.status,'pending');assert.equal(result.writes.length,0);});
test('ready evidence is attached and audited without marking verified; concurrent site changes reject',async()=>{const ready=await run();assert.equal(ready.res.statusCode,200);assert.equal(ready.writes.length,2);assert.match(ready.writes[0].sql,/INSERT INTO audit_events/);assert.doesNotMatch(ready.writes[1].sql,/verified_at|verification_status/);assert.equal(ready.writes[1].args[2],'data:image/png;base64,server');const changed=await run({race:true});assert.equal(changed.res.statusCode,409);assert.equal(changed.writes.length,0);});
