import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("hierarchy master renders report-wise and site-wise tick matrix", () => {
  const source = readFileSync(new URL("../src/main.jsx", import.meta.url), "utf8");
  const styles = readFileSync(new URL("../src/style.css", import.meta.url), "utf8");
  const hierarchySource = source.slice(source.indexOf("function HierarchyMasterPage"), source.indexOf("function RegionMasterPage"));

  assert.match(source, /function HierarchyMasterPage\(/);
  assert.match(source, /<HierarchyMasterPage records=\{records\}/);
  assert.match(hierarchySource, /Hierarchy Key Whatsapp Flow/);
  assert.match(hierarchySource, /Manage designation, level, location, reports, weekdays and WhatsApp delivery times/);
  assert.match(hierarchySource, /visibleReportGroups\.map/);
  assert.match(hierarchySource, /visibleReportTitles\.map/);
  assert.match(hierarchySource, /WCL and NCL site wise ticks/);
  assert.match(hierarchySource, /hierarchySiteGroups\.flatMap/);
  assert.match(hierarchySource, /hierarchySiteTitles/);
  assert.doesNotMatch(hierarchySource, /activeRegion\?\.sites/);
  assert.match(hierarchySource, /toggleReport/);
  assert.match(hierarchySource, /toggleSite/);
  assert.match(hierarchySource, /className="hierarchy-row-edit"/);
  assert.match(hierarchySource, /Edit hierarchy ·/);
  assert.match(hierarchySource, /saveHierarchyDetails/);
  assert.match(hierarchySource, /reportAccess: editingReports\.join\(" \| "\)/);
  assert.match(hierarchySource, /siteAccess: editingSites\.join\(" \| "\)/);
  assert.match(hierarchySource, /checked=\{editingReports\.includes\(report\)\}/);
  assert.match(hierarchySource, /checked=\{editingSites\.includes\(site\)\}/);
  assert.match(hierarchySource, /hasOwnProperty\.call\(stored, "reportAccess"\)/);
  assert.match(hierarchySource, /Reporting files/);
  assert.match(hierarchySource, /Save all changes/);
  assert.match(hierarchySource, /Report delivery schedule/);
  assert.match(hierarchySource, /Hierarchy &amp; report delivery/);
  assert.match(hierarchySource, /const customRows = records\.filter/);
  assert.match(hierarchySource, /const allRows = \[\.\.\.defaultRows, \.\.\.customRows\]/);
  assert.match(hierarchySource, /Scheduled delivery days/);
  assert.match(hierarchySource, /hierarchyStandardTimes\.map/);
  assert.match(hierarchySource, /\+ Custom time/);
  assert.match(hierarchySource, /scheduleDays: reportWeekDays\.filter/);
  assert.match(hierarchySource, /scheduleTimes: scheduleTimes\.join/);
  assert.match(source, /inOut: IN_OUT_REPORT_TITLE/);
  assert.match(hierarchySource, /settings saved successfully/);
  assert.match(hierarchySource, /className="hierarchy-save-error"/);
  assert.match(source, /for \(let attempt = 0; attempt < 3; attempt \+= 1\)/);
  assert.match(source, /The save connection was interrupted\. Please try again\./);
  assert.match(source, /hierarchyColumnViewOptions/);
  assert.match(source, /group:"MIS Report", viewKey:"S"/);
  assert.match(source, /key:"W", label:"WCL and NCL site-wise controls"/);
  assert.match(source, /hierarchyRowViewOptions/);
  assert.match(source, /hierarchyRowViewKey/);
  assert.match(hierarchySource, /visibleColumnGroups/);
  assert.match(hierarchySource, /visibleRowGroups/);
  assert.match(hierarchySource, /Visible hierarchy column groups/);
  assert.match(hierarchySource, /Visible hierarchy designation groups/);
  assert.match(hierarchySource, /showIdentityColumns/);
  assert.match(hierarchySource, /showSiteColumns = visibleColumnKeys\.has\("W"\)/);
  assert.match(source, /reportAccess/);
  assert.match(source, /siteAccess/);
  assert.match(styles, /\.hierarchy-master-page/);
  assert.match(styles, /\.hierarchy-matrix/);
  assert.match(styles, /\.hierarchy-view-controls/);
  assert.match(styles, /\.hierarchy-view-tab\.active/);
  assert.match(styles, /\.hierarchy-group-row th\.mis/);
  assert.match(styles, /\.hierarchy-col-schedule\{position:sticky!important;left:458px!important/);
  assert.match(styles, /\.hierarchy-report-legend/);
  assert.match(styles, /\.hierarchy-row-edit/);
  assert.match(styles, /\.hierarchy-edit-modal/);
  assert.match(styles, /\.hierarchy-access-grid/);
  assert.match(styles, /\.hierarchy-save-message/);
  assert.match(styles, /\.hierarchy-save-error/);
  assert.match(styles, /\.hierarchy-weekday-selector/);
  assert.match(styles, /\.hierarchy-time-selector/);
  assert.match(styles, /\.hierarchy-schedule-preview/);
});
