import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("hierarchy master renders report-wise and site-wise tick matrix", () => {
  const source = readFileSync(new URL("../src/main.jsx", import.meta.url), "utf8");
  const styles = readFileSync(new URL("../src/style.css", import.meta.url), "utf8");
  const hierarchySource = source.slice(source.indexOf("function HierarchyMasterPage"), source.indexOf("function RegionMasterPage"));

  assert.match(source, /function HierarchyMasterPage\(/);
  assert.match(source, /<HierarchyMasterPage records=\{records\}/);
  assert.match(hierarchySource, /Hierarchy Key Whatsapp Flow/);
  assert.match(hierarchySource, /Designation-wise WhatsApp report matrix/);
  assert.match(hierarchySource, /visibleReportGroups\.map/);
  assert.match(hierarchySource, /visibleReportTitles\.map/);
  assert.match(hierarchySource, /WCL and NCL site wise ticks/);
  assert.match(hierarchySource, /hierarchySiteGroups\.flatMap/);
  assert.match(hierarchySource, /hierarchySiteTitles/);
  assert.doesNotMatch(hierarchySource, /activeRegion\?\.sites/);
  assert.match(hierarchySource, /toggleReport/);
  assert.match(hierarchySource, /toggleSite/);
  assert.match(source, /hierarchyColumnViewOptions/);
  assert.match(source, /group:"MIS Report", viewKey:"S"/);
  assert.match(source, /key:"W", label:"WCL and NCL site-wise controls"/);
  assert.match(source, /hierarchyRowViewOptions/);
  assert.match(source, /hierarchyRowViewKey/);
  assert.match(hierarchySource, /visibleColumnGroups/);
  assert.match(hierarchySource, /visibleRowGroups/);
  assert.match(hierarchySource, /Visible hierarchy column groups/);
  assert.match(hierarchySource, /Visible hierarchy designation groups/);
  assert.match(hierarchySource, /showIdentityColumns/);
  assert.match(hierarchySource, /showSiteColumns = visibleColumnKeys\.has\("W"\)/);
  assert.match(source, /reportAccess/);
  assert.match(source, /siteAccess/);
  assert.match(styles, /\.hierarchy-master-page/);
  assert.match(styles, /\.hierarchy-matrix/);
  assert.match(styles, /\.hierarchy-view-controls/);
  assert.match(styles, /\.hierarchy-view-tab\.active/);
  assert.match(styles, /\.hierarchy-group-row th\.mis/);
  assert.match(styles, /\.hierarchy-col-schedule\{position:sticky!important;left:458px!important/);
  assert.match(styles, /\.hierarchy-report-legend/);
});
