import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

test("MIS users and managers use location-scoped requests, TAT, and partitioned first-trip KPIs",()=>{
  const source=fs.readFileSync(new URL("../src/main.jsx",import.meta.url),"utf8");
  const server=fs.readFileSync(new URL("../server.mjs",import.meta.url),"utf8");
  const manager=source.slice(source.indexOf("function ManagerDashboard"),source.indexOf("function Dashboard"));
  assert.match(server,/dashboardScope\|\|req\.session\.assignedRole==='MIS User'[\s\S]*scopedSite=String\(operationalUser\.site\|\|operationalUser\.location/);
  assert.match(server,/rows\.filter\(\(row\)=>canonicalSiteName\(row\.site\)===canonicalSiteName\(scopedSite\)\)/);
  assert.match(server,/A location must be assigned before this MIS user can verify requests/);
  assert.match(server,/canonicalSiteName\(existing\.site\)!==canonicalSiteName\(misSite\)/);
  assert.match(server,/This request belongs to a different location/);
  assert.match(server,/const firstTripCardImage=String\(req\.body\?\.firstTripCardImage\|\|''\)/);
  assert.match(server,/if\(!validTripCardImageDataUrl\(firstTripCardImage\)\)return res\.status\(400\)/);
  assert.match(source,/if \(!tripCardFile\) return alert\("Upload the first-trip card image\."\)/);
  assert.match(source,/First trip card image \*[\s\S]*name="firstTripCardImage"[\s\S]*required/);
  assert.match(source,/const submitLock = useRef\(false\)/);
  assert.match(source,/if \(submitLock\.current\) return/);
  assert.match(source,/await onSave\(\{firstTripDone/);
  assert.match(source,/submitting \? "Verifying…" : "Verify request"/);
  assert.match(source,/showClosedBy && workflowHeader\("closedBy", "Closed by"\)/);
  assert.match(source,/showClosedBy && <td>\{row\.closedBy \|\| "—"\}<\/td>/);
  assert.match(source,/showTripCard && workflowHeader\("tripCard", "Trip card image"\)/);
  assert.match(source,/<TripCardCell request=\{row\} \/>/);
  assert.match(source,/tab === "requests"[\s\S]*showReason showClosedBy showTurnaroundTime/);
  assert.match(source,/showVerifiedBy=\{isMis\} showTripCard=\{isMis\}/);
  assert.match(server,/app\.get\('\/api\/requests\/:reference\/trip-card'/);
  assert.match(server,/first_trip_card_image AS image/);
  assert.match(manager,/"Total requests", verifiedRequests\.length/);
  assert.doesNotMatch(manager,/"Pending verification"/);
  assert.doesNotMatch(manager,/\["Verified", verifiedRequests\.length/);
  assert.match(manager,/activeRows=activeManagerRole==="MIS Manager"\?pendingVerification:openRequests/);
  assert.match(manager,/historyRows=activeManagerRole==="MIS Manager"\?verifiedRequests:closedRequests/);
  assert.match(manager,/detailRows=queueTab==="history"\?historyRows:activeRows/);
  assert.match(manager,/showTurnaroundTime=\{activeManagerRole === "MIS Manager"\}/);
  assert.match(source,/showTurnaroundTime \? "Turn around time \(TAT\)" : "Downtime"/);
  assert.match(source,/isMis[\s\S]*<MobileWorkflowTable rows=\{visibleRows\} showMakeModel showTurnaroundTime/);
});
