import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";

test("request lifecycle has reason/status columns, closed history, and stakeholder notifications",()=>{
  const source=fs.readFileSync(new URL("../src/main.jsx",import.meta.url),"utf8");
  const mobileStyles=fs.readFileSync(new URL("../src/mobile-workflow.css",import.meta.url),"utf8");
  const server=fs.readFileSync(new URL("../server.mjs",import.meta.url),"utf8");
  const access=fs.readFileSync(new URL("../mobile-access.mjs",import.meta.url),"utf8");
  assert.match(source,/showReason \? \[\["complaint", "Reason"\]\]/);
  assert.match(source,/\["status", "Status"\]/);
  assert.match(source,/Closed history/);
  assert.match(source,/activeRequests=requests\.filter[\s\S]*!=="closed"/);
  assert.match(source,/historyRows=isMis\?closedRequests/);
  assert.match(source,/showReason && <th>Reason<\/th>/);
  assert.match(source,/showReason && <td>\{row\.complaint \|\| "—"\}<\/td>/);
  assert.match(source,/showCreatedBy && <th>Created by<\/th>/);
  assert.match(source,/showCreatedBy && <td>\{row\.owner \|\| row\.requesterLogin \|\| "—"\}<\/td>/);
  assert.match(source,/showClosedBy \? \[\["closedBy", "Closed by"\]\]/);
  assert.match(source,/showClosedBy && <td>\{row\.closedBy \|\| "—"\}<\/td>/);
  assert.match(source,/showVerifiedBy && <th>Verified by<\/th>/);
  assert.match(source,/showVerifiedBy && <td>\{row\.verifiedBy \|\| "—"\}<\/td>/);
  assert.match(source,/rows=\{activeRequests\} showReason showCreatedBy showBreakdownDays/);
  assert.match(source,/rows=\{historyRows\} showReason showCreatedBy showClosedBy showBreakdownDays/);
  assert.match(mobileStyles,/\.normal \.table \.mobile-breakdown-table th,[\s\S]*display: table-cell/);
  assert.match(source,/rows=\{activeRequests\} showReason showCreatedBy showComplaintAudio/);
  assert.match(source,/rows=\{visibleRows\} showReason showClosedBy showTurnaroundTime/);
  assert.match(source,/showClosedBy showVerifiedBy=\{isMis\} showTripCard=\{isMis\}/);
  assert.match(source,/showReason=\{isMaintenance \|\| isMis\} showClosedBy showVerifiedBy=\{isMis\}/);
  assert.match(source,/showReason=\{activeManagerRole === "Production Manager"\} showClosedBy=\{queueTab==="history"\}/);
  assert.match(access,/"Closed history"/);
  assert.match(server,/async function requestStakeholderLogins/);
  assert.match(server,/profile\.permissions\.adminLevel==='Manager'&&userManagesSite\(user,site\)/);
  assert.match(server,/\['Production User','Maintenance User','MIS User'\]/);
  assert.match(server,/const openedAt=requestNotificationTime\(startedAt\)/);
  assert.match(server,/Date & time: \$\{openedAt\}/);
  assert.match(server,/const closedAtLabel=requestNotificationTime\(closedAt\)/);
  assert.match(server,/Closing date & time: \$\{closedAtLabel\}/);
});
