import React,{useEffect,useState} from 'react';
import {Trash2,RefreshCw,X} from 'lucide-react';
import {formatDisplayDateTime} from '../date-time-format.mjs';
import './employee-transfer.css';
export default function CdirDeletion({token,ReportSection}){
 const [data,setData]=useState({token,loading:true,records:[],targets:[]}),[view,setView]=useState('Pending'),[search,setSearch]=useState(''),[targetSearch,setTargetSearch]=useState(''),[form,setForm]=useState(false),[working,setWorking]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState(null),[action,setAction]=useState(null);
 const api=async(path='',method='GET',body)=>{const response=await fetch('/api/cdir/deletion-requests'+path,{method,cache:'no-store',headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw Error(result.error||'Could not update deletion requests.');return result;};
 const load=async()=>{try{setData(current=>({...current,loading:true}));setData({...await api(),token,loading:false});}catch(err){setData({token,loading:false,records:[],targets:[]});setError(err.message);}};
 useEffect(()=>{setForm(false);setSelected(null);setAction(null);setError('');void load();},[token]);
 const submit=async event=>{event.preventDefault();if(working)return;const values=new FormData(event.currentTarget),target=data.targets.find(row=>`${row.master}|${row.id}`===values.get('target'));if(!target)return;setWorking(true);setError('');try{const result=await api('','POST',{master:target.master,recordId:target.id,reason:values.get('reason')});setNotice(`${result.requestNo} sent for approval. The record is retained until approval.`);setForm(false);await load();}catch(err){setError(err.message);}finally{setWorking(false);}};
 const decide=async event=>{event.preventDefault();if(working)return;setWorking(true);setError('');try{await api(`/${action.record.id}/${action.verb}`,'PATCH',{note:new FormData(event.currentTarget).get('note')});setNotice(action.verb==='approve'?'Deletion approved and record deleted.':'Deletion rejected; record retained.');setAction(null);await load();}catch(err){setError(err.message);}finally{setWorking(false);}};
 const rows=data.records.filter(row=>view==='All'||view==='Pending'?view==='All'||row.status==='Pending':row.status!=='Pending');
 const columns=[['requestNo','Request'],['master','Record type'],['empId','Employee ID'],['name','Employee'],['site','Location'],['approverRole','Approver role'],['reason','Deletion reason'],['status','Status'],['requestedBy','Requested by'],['requestedAt','Requested at'],['decidedBy','Decided by'],['decidedAt','Decision at'],['decisionNote','Decision remarks']].map(([key,label])=>({key,label,value:row=>key.endsWith('At')?formatDisplayDateTime(row[key]):row[key]||''}));
 columns.unshift({key:'actions',label:'Actions',value:row=>row.canApprove?'Approval required':'View history',render:row=><div className="et-actions"><button onClick={()=>setSelected(row)}>History</button>{row.canApprove&&<><button onClick={()=>{setAction({record:row,verb:'approve'});setError('');}}>Approve deletion</button><button onClick={()=>{setAction({record:row,verb:'reject'});setError('');}}>Reject</button></>}</div>});
 return <section className="employee-transfer"><header className="et-heading"><div><small>C-DIRECTORY</small><h1><Trash2/>Record Deletion Approvals</h1><p>HR Manager approval for Nagpur/Chandrapur; Project Manager approval for other locations. Admins can delete directly in Masters.</p></div><div><button disabled={working} onClick={load}><RefreshCw/>Refresh</button><button className="primary" disabled={data.loading||data.token!==token||!data.targets.length} onClick={()=>{setForm(true);setTargetSearch('');setError('');}}>Request deletion</button></div></header>{notice&&<p role="status" className="et-notice">{notice}</p>}{error&&<p role="alert" className="et-error">{error}</p>}{data.loading||data.token!==token?<p role="status">Loading deletion requests…</p>:<><div className="et-tabs">{['Pending','History','All'].map(tab=><button key={tab} aria-pressed={view===tab} onClick={()=>setView(tab)}>{tab}</button>)}</div><label className="et-search">Search<input data-smart-search type="search" value={search} onChange={event=>setSearch(event.target.value)}/></label><ReportSection title={`C-Directory Deletion Requests · ${view}`} category="cdir-deletion" query={search} showSearch={false} rows={rows} columns={columns} rowKey={row=>row.id}/></>}
 {form&&data.token===token&&<div className="et-backdrop"><section className="et-dialog et-confirm" role="dialog" aria-modal="true" aria-label="Request record deletion"><header><h2>Request deletion</h2><button disabled={working} aria-label="Close request form" onClick={()=>setForm(false)}><X/></button></header><form onSubmit={submit}><label>Find employee or contact<input type="search" placeholder="Employee ID, name or location" value={targetSearch} onChange={event=>setTargetSearch(event.target.value)}/></label><label>Employee or contact record<select name="target" required defaultValue=""><option value="">Select record</option>{data.targets.filter(row=>[row.empId,row.name,row.site,row.master].join(" ").toLowerCase().includes(targetSearch.toLowerCase())).map(row=><option key={`${row.master}|${row.id}`} value={`${row.master}|${row.id}`}>{row.empId||'No ID'} · {row.name} · {row.site} · {row.master.includes('Contact')?'Contact':'Employee'}</option>)}</select></label><label>Deletion reason<textarea name="reason" required maxLength={2000} rows={4}/></label><p>The record remains available until the assigned location manager approves deletion.</p>{error&&<p role="alert">{error}</p>}<footer><button className="primary" disabled={working}>{working?'Submitting…':'Send for approval'}</button></footer></form></section></div>}
 {action&&data.token===token&&<div className="et-backdrop"><section className="et-dialog et-confirm" role="dialog" aria-modal="true" aria-label="Deletion decision"><header><h2>{action.verb==='approve'?'Approve deletion':'Reject deletion'}</h2><button disabled={working} aria-label="Close decision" onClick={()=>setAction(null)}><X/></button></header><p>{action.record.empId} · {action.record.name} · {action.record.site}</p><p>Reason: {action.record.reason}</p>{action.verb==='approve'&&<p>Approval permanently deletes this {action.record.master.includes('Contact')?'contact':'employee'} record. Its snapshot and approval history will be retained.</p>}<form onSubmit={decide}><label>Decision remarks<textarea name="note" rows={3} required={action.verb==='reject'} maxLength={2000}/></label>{error&&<p role="alert">{error}</p>}<footer><button className="primary" disabled={working}>{working?'Saving…':'Confirm'}</button></footer></form></section></div>}
 {selected&&data.token===token&&<div className="et-backdrop"><section className="et-dialog" role="dialog" aria-modal="true" aria-label="Deletion history"><header><h2>{selected.requestNo} · {selected.name}</h2><button aria-label="Close deletion history" onClick={()=>setSelected(null)}><X/></button></header><p>{selected.site} · {selected.status} · {selected.reason}</p><ReportSection title={`${selected.requestNo} · Record snapshot`} category="cdir-deletion-details" columns={[{key:'field',label:'Field',value:row=>row.field},{key:'value',label:'Recorded value',value:row=>row.value}]} rows={Object.entries(selected.record).map(([field,value])=>({field,value:typeof value==='object'?JSON.stringify(value):String(value??'')}))}/><ReportSection title={`${selected.requestNo} · Approval history`} category="cdir-deletion-history" columns={[{key:'action',label:'Action',value:row=>row.action},{key:'by',label:'By',value:row=>row.by},{key:'at',label:'Date & time',value:row=>formatDisplayDateTime(row.at)},{key:'note',label:'Remarks',value:row=>row.note}]} rows={selected.history}/></section></div>}
 </section>;
}
