import React,{useEffect,useState} from 'react';
import {ArrowRightLeft,BookUser,Users,Search,RefreshCw,Send,X} from 'lucide-react';
import {formatDisplayDate,formatDisplayDateTime} from '../date-time-format.mjs';
import DateInput from './date-input.mjs';
import './employee-transfer.css';
import CaliberDirectoryPage from './caliber-directory-page.jsx';
import EmployeeTenureReport from './employee-tenure-report.jsx';
import {CDIR_MASTER_FIELDS,CDIR_MASTERS} from '../cdir-masters.mjs';
const detailLabels=Object.fromEntries([...CDIR_MASTER_FIELDS[CDIR_MASTERS.employee],...CDIR_MASTER_FIELDS[CDIR_MASTERS.contact]].map(([key,label])=>[key,label]));

export function CdirModule({token,ReportSection,initialView='directory',onViewChange}){
  const [view,setView]=useState(initialView);const allowed=useEmployeeTransferAccess(token);
  useEffect(()=>setView(initialView),[initialView]);
  return <><div className="cdir-module-tabs" role="tablist" aria-label="C-Directory pages">{[['directory','Directory'],['tenure','Employee Tenure Report'],...(allowed?[['transfer','Employee Transfer']]:[])].map(([key,label])=><button key={key} type="button" role="tab" aria-selected={view===key} className={view===key?'active':''} onClick={()=>{setView(key);onViewChange?.(key);}}>{key==='directory'?<BookUser/>:key==='tenure'?<Users/>:<ArrowRightLeft/>}{label}</button>)}</div>{view==='transfer'&&allowed?<EmployeeTransfer token={token} ReportSection={ReportSection}/>:view==='tenure'?<EmployeeTenureReport token={token} ReportSection={ReportSection}/>:<CaliberDirectoryPage token={token}/>}</>;
}

export function useEmployeeTransferAccess(token){
  const [access,setAccess]=useState({token:null,allowed:false});
  useEffect(()=>{let alive=true;fetch('/api/cdir/employee-transfer-access',{cache:'no-store',headers:{Authorization:`Bearer ${token}`}}).then(async response=>{if(!response.ok)throw Error();return response.json();}).then(body=>{if(alive)setAccess({token,allowed:body.allowed===true});}).catch(()=>{if(alive)setAccess({token,allowed:false});});return()=>{alive=false;};},[token]);
  return access.token===token&&access.allowed;
}
async function api(token,path,method='GET',body){
  const response=await fetch(`/api/cdir/${path}`,{method,cache:'no-store',headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'Could not complete the employee transfer action.');return data;
}
export default function EmployeeTransfer({token,ReportSection}){
  const [data,setData]=useState({token,records:[],sites:[],loading:true,error:''});
  const [view,setView]=useState('All'),[query,setQuery]=useState(''),[form,setForm]=useState(false),[empId,setEmpId]=useState(''),[employee,setEmployee]=useState(null),[details,setDetails]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState(null),[action,setAction]=useState(null),[note,setNote]=useState('');
  const load=async()=>{setData(current=>({...current,loading:true,error:''}));try{const result=await api(token,'employee-transfers');setData({...result,token,loading:false,error:''});}catch(err){setData({token,records:[],sites:[],loading:false,error:err.message});}};
  useEffect(()=>{setSelected(null);setEmployee(null);setForm(false);void load();},[token]);
  const lookup=async event=>{event.preventDefault();if(busy)return;setBusy(true);setEmployee(null);setError('');try{const result=await api(token,`employee-transfers/lookup?empId=${encodeURIComponent(empId.trim())}`);setEmployee(result);setDetails(result.record);}catch(err){setError(err.message);}finally{setBusy(false);}};
  const submit=async event=>{event.preventDefault();if(busy||!employee)return;setBusy(true);setError('');const values=new FormData(event.currentTarget);try{const result=await api(token,'employee-transfers','POST',{employeeRecordId:employee.employeeRecordId,revision:employee.revision,record:details,destination:values.get('destination'),effectiveDate:values.get('effectiveDate'),remarks:values.get('remarks')});setNotice(`${result.transferNo} created. Outgoing and incoming requests sent to the assigned Project Managers.`);setForm(false);setEmployee(null);await load();}catch(err){setError(err.message);}finally{setBusy(false);}};
  const act=async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');try{await api(token,`employee-transfers/${action.record.id}/${action.verb}`,'PATCH',{note});setNotice(action.verb==='accept'?'Transfer completed. Employee details and location updated.':'Transfer request updated.');setAction(null);setSelected(null);await load();}catch(err){setError(err.message);}finally{setBusy(false);}};
  const rows=data.records.filter(row=>view==='All'||view==='Outgoing'?view==='All'||row.outgoing:view==='Incoming'?row.incoming:['Completed','Rejected'].includes(row.status));
  const columns=[['transferNo','Request'],['empId','Employee ID'],['name','Employee'],['source','From location'],['destination','To location'],['effectiveDate','Transfer date'],['status','Status'],['submittedBy','Requested by'],['submittedAt','Requested at'],['approvedBy','Source approved by'],['approvedAt','Source approved at'],['acceptedBy','Destination accepted by'],['acceptedAt','Accepted at'],['rejectionReason','Rejection reason'],['remarks','Remarks']].map(([key,label])=>({key,label,value:row=>key==='effectiveDate'?formatDisplayDate(row[key]):key.endsWith('At')?formatDisplayDateTime(row[key]):row[key]||'',...(key==='transferNo'?{render:row=><button className="et-link" onClick={()=>setSelected(row)}>{row.transferNo}</button>}:{})}));
  columns.unshift({key:'actions',label:'Actions',value:row=>row.canApprove?'Approve outgoing':row.canAccept?'Accept incoming':'View history',render:row=><div className="et-actions"><button onClick={()=>setSelected(row)}>History</button>{(row.canApprove||row.canAccept)&&<><button onClick={()=>{setAction({record:row,verb:row.canApprove?'approve':'accept'});setNote('');setError('');}}>{row.canApprove?'Approve outgoing':'Accept incoming'}</button><button onClick={()=>{setAction({record:row,verb:'reject'});setNote('');setError('');}}>Reject</button></>}</div>});
  const tabs=<div className="et-tabs">{['All','Outgoing','Incoming','History'].map(label=><button type="button" aria-pressed={view===label} key={label} onClick={()=>setView(label)}>{label}</button>)}</div>;
  return <section className="employee-transfer"><header className="et-heading"><div><small>C-DIRECTORY</small><h1><ArrowRightLeft/>Employee Transfer</h1><p>Source PM approval → Destination PM acceptance → Employee location updated.</p></div><div><button onClick={load} disabled={data.loading||busy}><RefreshCw/>Refresh</button>{data.capabilities?.canSubmit&&<button className="primary" onClick={()=>{setForm(true);setEmployee(null);setEmpId('');setError('');}}><Send/>New transfer</button>}</div></header>{notice&&<p role="status" className="et-notice">{notice}</p>}
    {data.loading||data.token!==token?<p role="status">Loading employee transfers…</p>:data.error?<p role="alert">{data.error}</p>:<><label className="et-search">Search requests<input type="search" data-smart-search value={query} onChange={event=>setQuery(event.target.value)} placeholder="Employee ID, name, location or request"/></label><ReportSection title={`Employee Transfers · ${view}`} headingControl={tabs} category="employee-transfer" description="Select a request to view its employee details and complete approval history. Export, PDF and print include the current table selection." query={query} showSearch={false} columns={columns} rows={rows} rowKey={row=>row.id}/></>}
    {form&&<div className="et-backdrop"><section className="et-dialog" role="dialog" aria-modal="true" aria-label="New employee transfer"><header><h2>New employee transfer</h2><button disabled={busy} aria-label="Close transfer form" onClick={()=>setForm(false)}><X/></button></header><form className="et-lookup" onSubmit={lookup}><label>Employee ID<input required maxLength={80} value={empId} disabled={busy} onChange={event=>{setEmpId(event.target.value);setEmployee(null);}}/></label><button disabled={busy}><Search/>{busy?'Loading…':'Find employee'}</button></form>{error&&<p role="alert" className="et-error">{error}</p>}{employee&&<form onSubmit={submit}><p className="et-notice">{employee.empId} · From {employee.source}. Changes below are applied only after destination acceptance.</p><div className="et-grid">{employee.fields.map(field=><label key={field.key}>{field.label}{field.options?<select value={details[field.key]} disabled={busy} onChange={event=>setDetails({...details,[field.key]:event.target.value})}><option value="">Select</option>{[...new Set([details[field.key],...field.options].filter(Boolean))].map(value=><option key={value}>{value}</option>)}</select>:field.type==='date'?<DateInput value={details[field.key]} disabled={busy} onChange={event=>setDetails({...details,[field.key]:event.target.value})}/>:<input value={details[field.key]} maxLength={500} disabled={busy} required={field.key==='name'} onChange={event=>setDetails({...details,[field.key]:event.target.value})}/>}</label>)}<label>Where to transfer<select name="destination" required disabled={busy} defaultValue=""><option value="">Select destination</option>{data.sites.filter(site=>site!==employee.source).map(site=><option key={site}>{site}</option>)}</select></label><label>Transfer date<DateInput name="effectiveDate" required disabled={busy}/></label><label className="et-full">Remarks<textarea name="remarks" maxLength={2000} rows={3} disabled={busy}/></label></div><footer><button disabled={busy} className="primary"><Send/>{busy?'Submitting…':'Create transfer request'}</button></footer></form>}</section></div>}
    {selected&&<div className="et-backdrop"><section className="et-dialog" role="dialog" aria-modal="true" aria-label="Employee transfer history"><header><h2>{selected.transferNo} · {selected.name}</h2><button aria-label="Close transfer history" onClick={()=>setSelected(null)}><X/></button></header><p>{selected.source} → {selected.destination} · {selected.status}</p><ReportSection title={`${selected.transferNo} · Employee details`} category="employee-transfer-details" columns={[{key:'field',label:'Field',value:row=>row.field},{key:'before',label:'Before transfer',value:row=>row.before},{key:'after',label:'Requested details',value:row=>row.after}]} rows={[...Object.keys(selected.proposed),...Object.keys(selected.proposedContact).filter(key=>!['name','empId'].includes(key))].filter(key=>!['rank','order'].includes(key)).map(key=>({field:detailLabels[key]||key,before:selected.before[key]??selected.beforeContact?.record_data[key]??'',after:selected.proposed[key]??selected.proposedContact[key]??''}))}/><ReportSection title={`${selected.transferNo} · Approval history`} category="employee-transfer-history" columns={[{key:'action',label:'Action',value:row=>row.action},{key:'by',label:'By',value:row=>row.by},{key:'login',label:'Login',value:row=>row.login},{key:'at',label:'Date & time',value:row=>formatDisplayDateTime(row.at)},{key:'note',label:'Remarks',value:row=>row.note}]} rows={selected.history}/></section></div>}
    {action&&<div className="et-backdrop"><section className="et-dialog et-confirm" role="dialog" aria-modal="true" aria-label="Confirm transfer action"><header><h2>{action.verb==='reject'?'Reject request':action.verb==='approve'?'Approve outgoing transfer':'Accept incoming transfer'}</h2><button disabled={busy} aria-label="Close action" onClick={()=>setAction(null)}><X/></button></header><p>{action.record.empId} · {action.record.name}<br/>{action.record.source} → {action.record.destination}</p><form onSubmit={act}><label>Remarks{action.verb==='reject'?' (required)':''}<textarea rows={3} value={note} required={action.verb==='reject'} maxLength={2000} disabled={busy} onChange={event=>setNote(event.target.value)}/></label>{error&&<p role="alert" className="et-error">{error}</p>}<footer><button disabled={busy} className="primary">{busy?'Saving…':'Confirm'}</button></footer></form></section></div>}
  </section>;
}
