import React from 'react';
import {ArrowUpRight,ChartColumn,Wallet,CheckCheck} from 'lucide-react';
import {chartMagnitude,chartScale,adviceCompletion} from './iboss-chart-values.mjs';
import './iboss-finance-charts.css';
export default function FinanceCharts({data,formatAmount,onSelect,onAdvice}){
 const trade=['trade-payable','trade-receivable'].map(key=>data.cards.find(card=>card.key===key));
 const emi=['overdue-emi','upcoming-emi'].map(key=>data.cards.find(card=>card.key===key));
 const maximum=chartScale(trade.map(card=>card?.amount)),emiMax=chartScale(emi.map(card=>card?.amount));
 const advice=adviceCompletion(data.advice);
 return <section className="finance-charts" aria-label="Financial charts">
 <article className="finance-chart trade-chart"><header><span className="finance-chart-icon"><ChartColumn/></span><div><small>LEDGER POSITION</small><h3>Trade balances</h3></div></header><p>Absolute net balances through the selected closing date</p>
 <div className="finance-columns"><div className="finance-grid-lines" aria-hidden="true"><i/><i/><i/><i/></div>{trade.map((card,index)=>card&&<button key={card.key} className={`finance-column column-${index}`} onClick={()=>onSelect(card.key)} aria-label={`Open ${card.title}: ${formatAmount(card.amount)} ${card.balanceSide||''}`}><span className="finance-column-value">{formatAmount(card.amount)}<em>{card.balanceSide||''}</em></span><span className="finance-column-track"><span style={{height:`${(chartMagnitude(card.amount)??0)/maximum*100}%`}}/></span><span className="finance-column-label">{index?'Receivables':'Payables'}<ArrowUpRight/></span></button>)}</div><footer>Bar heights compare magnitudes; Dr / Cr shows the balance side.</footer></article>
 <article className="finance-chart"><header><span className="finance-chart-icon amber"><Wallet/></span><div><small>PAYMENT PLANNING</small><h3>EMI commitments</h3></div></header><p>Unpaid instalments relative to your planning date</p><div className="finance-emi-bars">{emi.map((card,index)=>card&&<button key={card.key} onClick={()=>onSelect(card.key)} className={index?'upcoming':'overdue'}><span className="finance-emi-label">{index?'Due in next 30 days':'Overdue'}<ArrowUpRight/></span><strong>{formatAmount(card.amount)}</strong><span className="finance-emi-track" aria-hidden="true"><i style={{width:`${(chartMagnitude(card.amount)??0)/emiMax*100}%`}}/></span><span className="finance-emi-count">{card.count?.toLocaleString('en-IN')??'—'} instalments</span></button>)}</div><footer>Open a bar to review the underlying EMI records.</footer></article>
 <article className="finance-chart"><header><span className="finance-chart-icon mint"><CheckCheck/></span><div><small>WORKFLOW STATUS</small><h3>Payment advice</h3></div></header><p>Advice created within the selected voucher period</p><button type="button" className="finance-donut-button" onClick={onAdvice} aria-label={`Open payment advice: ${advice.completed} completed, ${advice.pending} pending`}><span className="finance-donut"><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="48" className="finance-donut-track"/>{advice.total>0&&<><circle cx="60" cy="60" r="48" className="finance-donut-pending"/><circle cx="60" cy="60" r="48" className="finance-donut-complete" pathLength="100" strokeDasharray={`${advice.percent} 100`} transform="rotate(-90 60 60)"/></>}</svg><span><strong>{advice.percent==null?'—':`${Math.round(advice.percent)}%`}</strong><small>{advice.total?'completed':'No advice'}</small></span></span></button><div className="finance-donut-legend"><span><i/>{advice.completed.toLocaleString('en-IN')} completed</span><span><i/>{advice.pending.toLocaleString('en-IN')} pending</span></div><footer>ERP completion flag · {advice.total.toLocaleString('en-IN')} advice records <ArrowUpRight/></footer></article>
 </section>;
}
