import {ledgerReportColumns} from './iboss-ledger-report.mjs';
import React,{useEffect,useRef,useState} from 'react';
import DrillPanel from './iboss-drill-panel.jsx';
import DateInput from './date-input.mjs';
import {purchaseOrderRange} from '../purchase-order-report.mjs';
import {formatDisplayDate} from '../date-time-format.mjs';
import './iboss-account-ledger.css';
import {splitLedgerBalance,ledgerFooter} from './iboss-ledger-format.mjs';
const money=v=>Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const balance=v=>Number(v||0)===0?money(0):`${money(Math.abs(Number(v||0)))} ${Number(v)<0?'Dr':'Cr'}`;
export default function AccountLedger({account,company,range:initialRange,token,close,ReportSection}){
 const [reportView,setReportView]=useState(false);
 const dialog=useRef(null),[range,setRange]=useState(initialRange),[draft,setDraft]=useState(initialRange),[page,setPage]=useState(0),[data,setData]=useState({loading:true}),[error,setError]=useState(''),[voucher,setVoucher]=useState(null),[showNarration,setShowNarration]=useState(true),[showAudit,setShowAudit]=useState(false);
 useEffect(()=>{const opener=document.activeElement;dialog.current.showModal();return ()=>{if(opener?.isConnected)opener.focus();};},[]);
 useEffect(()=>{const controller=new AbortController();setData({loading:true});fetch(`/api/reports/iboss-account-ledger?${new URLSearchParams({account,company,from:range.from,to:range.to,page})}`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Could not load the Oracle ledger. Please retry.');return r.json();}).then(body=>setData(body)).catch(e=>{if(!controller.signal.aborted)setData({error:e.message});});return ()=>controller.abort();},[account,company,range,page,token]);
 const totals=(data.balances||[]).reduce((s,r)=>{for(const k of Object.keys(s))s[k]+=Number(r[k]||0);return s;},{OPENING_BALANCE:0,DEBITAMOUNT:0,CREDITAMOUNT:0,BALANCEAMOUNT:0});
 const footer=ledgerFooter(totals);
 const amountCells=value=>{const sides=splitLedgerBalance(value);return <><td className="ledger-number">{sides.debit?money(sides.debit):''}</td><td className="ledger-number">{sides.credit?money(sides.credit):''}</td></>;};
 return <dialog ref={dialog} className="account-ledger-dialog" onCancel={e=>{e.preventDefault();e.stopPropagation();if(voucher)setVoucher(null);else close();}} aria-labelledby="account-ledger-title">
 <header><div><small>Account Ledger Revised · Read only</small><h2 id="account-ledger-title">{data.account?.PARTYNAME||account}</h2><p>Account: {account} · {data.account?.PARTYTYPENAME||'Account'} · Company: {company||'All companies'}</p></div><button onClick={close} aria-label="Close account ledger">×</button></header>
 <form onSubmit={e=>{e.preventDefault();try{purchaseOrderRange(draft.from,draft.to);setError('');setPage(0);setRange({...draft});}catch(e){setError(e.message);}}}><label>From<DateInput value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}/></label><label>To<DateInput value={draft.to} onChange={e=>setDraft({...draft,to:e.target.value})}/></label><button>Apply / Refresh</button></form>
 {error&&<p role="alert">{error}</p>}
 {data.loading?<p role="status">Loading ledger and audit details from Oracle…</p>:data.error?<p role="alert">{data.error}</p>:<>
 <p>Account created by: {data.account?.CREATOR_NAME||data.account?.CREATOR||'Not recorded'} {data.account?.CREATOR_NAME&&data.account?.CREATOR?`(${data.account.CREATOR})`:''} · Created: {data.account?.CREATED_AT||'Not recorded'}</p>
 <div className="account-ledger-totals"><span>Opening / B/F<strong>{balance(totals.OPENING_BALANCE)}</strong></span><span>Period debit<strong>{money(totals.DEBITAMOUNT)}</strong></span><span>Period credit<strong>{money(totals.CREDITAMOUNT)}</strong></span><span>Closing<strong>{balance(totals.BALANCEAMOUNT)}</strong></span></div>
 <p>Total: {Number(data.totalCount||0).toLocaleString('en-IN')} entries · {data.rows.length} loaded. Totals cover the full period. Click a voucher for its complete transaction details.</p>
 {ReportSection&&<div className="account-ledger-options" role="group" aria-label="Ledger view"><button type="button" aria-pressed={!reportView} onClick={()=>setReportView(false)}>ERP layout</button><button type="button" aria-pressed={reportView} onClick={()=>setReportView(true)}>Report table · Actions / Print/Export</button></div>}
 {reportView&&ReportSection?<ReportSection title="Account ledger transactions" category="iboss-accounts" rows={data.rows} description={'Account '+account+' · '+formatDisplayDate(range.from)+' to '+formatDisplayDate(range.to)+' · Filters, sorting and export apply to loaded entries. Running balances retain ERP chronological order.'} columns={ledgerReportColumns().map(column=>column.key==='VOUCHERNO'?{...column,render:r=><button type="button" className="iboss-detail-link" onClick={()=>setVoucher({chain:'voucher',key:String(r.TNO),focus:{step:'voucher',docNo:r.VOUCHERNO}})}>{r.VOUCHERNO}</button>}:column)} rowKey={r=>String(r.TNO)+':'+String(r.SNO)}/>:<>
 <div className="account-ledger-options"><label><input type="checkbox" checked={showNarration} onChange={e=>setShowNarration(e.target.checked)}/> Show narration</label><label><input type="checkbox" checked={showAudit} onChange={e=>setShowAudit(e.target.checked)}/> Show transaction creator and date/time</label></div>
 <div className="account-ledger-table"><table aria-label="Account Ledger Revised"><colgroup><col className="ledger-date"/><col className="ledger-location"/><col className="ledger-account"/><col className="ledger-voucher"/><col span="4" className="ledger-amount"/></colgroup><thead><tr><th rowSpan="2" scope="col">Date</th><th rowSpan="2" scope="col">Location</th><th rowSpan="2" scope="col">Account</th><th rowSpan="2" scope="col">Voucher No. / Party Bill No.</th><th colSpan="2" scope="colgroup">Amount</th><th colSpan="2" scope="colgroup">Balance</th></tr><tr>{['Dr','Cr','Dr','Cr'].map((x,i)=><th key={i} scope="col">{x}</th>)}</tr></thead><tbody>
 {page===0&&<tr className="ledger-opening"><td></td><td></td><th scope="row">B/F</th><td></td>{amountCells(totals.OPENING_BALANCE)}<td></td><td></td></tr>}
 {data.rows.map(r=><React.Fragment key={String(r.TNO)+':'+String(r.SNO)}><tr className="ledger-entry"><td>{formatDisplayDate(r.VOUCHER_DATE)}</td><td>{r.LOCATIONNAME||'—'}</td><td>{r.COUNTERPART_ACCOUNTS||'—'}</td><td><button className="iboss-detail-link" onClick={()=>setVoucher({chain:'voucher',key:String(r.TNO),focus:{step:'voucher',docNo:r.VOUCHERNO}})}>{r.VOUCHERNO}</button>{!showNarration&&r.BILLNO&&<small>{r.BILLNO}</small>}</td>{amountCells(r.AMOUNT)}{amountCells(r.RUNNING_BALANCE)}</tr>
 {showNarration&&<tr className="ledger-narration"><td></td><td></td><td>{r.NARRATION||'—'}</td><td>{r.BILLNO||''}</td><td colSpan="4"></td></tr>}
 {showAudit&&<tr className="ledger-audit"><td colSpan="8">Created by: {r.CREATOR_NAME||r.CREATOR||'Not recorded'}{r.CREATOR_NAME&&r.CREATOR? ' ('+r.CREATOR+')':''} · Created date / time (ERP): {r.CREATED_AT||'Not recorded'}</td></tr>}
 </React.Fragment>)}</tbody><tfoot><tr><th colSpan="4" scope="row">Total (Excluding Opening)</th><td className="ledger-number">{money(footer.periodDebit)}</td><td className="ledger-number">{money(footer.periodCredit)}</td><td colSpan="2"></td></tr><tr><th colSpan="4" scope="row">Total (Including Opening)</th><td className="ledger-number">{money(footer.totalDebit)}</td><td className="ledger-number">{money(footer.totalCredit)}</td>{amountCells(totals.BALANCEAMOUNT)}</tr></tfoot></table></div></>}
 {!data.rows.length&&<p>No transactions in this period.</p>}<nav><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={!data.hasMore} onClick={()=>setPage(p=>p+1)}>Next</button></nav>
 </>}{voucher&&<DrillPanel target={voucher} range={{...range,company}} token={token} close={()=>setVoucher(null)}/>}</dialog>;
}
